title: Recruiter by Day, Beginner Coder by Night
author: Faith New GitHub User
description: > # Recruiter by Day, Beginner Coder by Night


show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
